### PR TITLE
Add new script and readme updates

### PR DESCRIPTION
**Pull request by bhazelton**
I've added my new script and the readme updates to this PR. 

@adampbeardsley I'll add the data files and the deletions of the old data and code to this branch when you've reviewed the script in order to minimize the number of large data files that get added to the repo history.

### CODE REVIEW

**Comment by bhazelton** [comment]
@nkern can you look at this too? I don't want to mess you up, but there are some differences in the beam this script generates.

**Comment by nkern** [comment]
I'm fine with this, as long as the new `NF_HERA_power_beam_healpix.fits` has the same data in the same format as the old `NF_HERA_Beam.beamfits` file, but I can't tell b/c it isn't committed.

**Comment by bhazelton** [comment]
@nkern It has similar but not exactly the same data. I didn't want to commit it until we agreed on it because the files are large. The differences I know about are:
-- it includes all the frequencies (50-250 MHz). You can easily down select on the object (using the `select` method) once you read it in, but I wanted to make it general for other users.
-- It's not peak normalized. Again you can change that with the `peak_normalize` method once you read it in, but it's not something you can undo, so I wanted to leave it general for other users.

**Comment by bhazelton** [comment]
I'll put the beam files the new script generates on google drive and send you a link to them @nkern

**Comment by nkern** [comment]
I see, sounds like a smart thing to do. the files look good to me, so feel free to merge!

**Pull request merged**
